# Site settings
author: Leah Silber
title: Learning All The Things
header-img: img/home-bg.png
email: leahsilber@gmail.com
copyright_name: Leah Silber
description: > # this means to ignore newlines until "baseurl:"
  Thoughts along the way
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: wifelette
github_username:  wifelette

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
